// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjbxuuvdtmaxuoyxlkdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqYnh1dXZkdG1heHVveXhsa2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDIzNjksImV4cCI6MjA1ODExODM2OX0.eKRja5MR1aXl4MlPI324_QQHfiNu1SFm7BWnbBvDL3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);